version: '3.3'

services:
  service_author:
    build: 
      context: service_author
      dockerfile: Dockerfile
    container_name: service_author
    networks:
      - arch-network    
    ports:
      - 8081:8081
    restart: always
    #command: python3 -m uvicorn service_author:app --host 0.0.0.0 --reload --port 8081
    volumes:
      - ./service_author:/service_author

  service_presentation:
    build:
      context: service_presentation
      dockerfile: Dockerfile
    container_name: service_presentation
    networks:
      - arch-network
    ports:
      - 8082:8082
    #command: python3 -m uvicorn service_presentation:app --host 0.0.0.0 --reload --port 8082
    restart: always
    volumes:
      - ./service_presentation:/service_presentation
    
  service_main:
    build:
      context: service_main
      dockerfile: Dockerfile
    container_name: service_main
    depends_on:
      - service_presentation
      - service_author
    networks:
      - arch-network
    ports:
      - 8083:8083
    #command: python3 -m uvicorn service_main:app --host 0.0.0.0 --reload --port 8083
    restart: always
    volumes:
      - ./service_main:/service_main
    
networks:
  arch-network:
    driver: "bridge"
    external: false